name: CI

on:
  push:
    branches:
      - 'main'
env:
  NODE_VERSION: '16'  # Set Node.js version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        run: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: custom_surrogate/
          push: true
          tags: monabraeunig/surrogate-container2:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      model:
        image: monabraeunig/surrogate-container2:latest
        ports:
          - 4242:4242

    steps:
      - name: Validate
        run: |
          docker run --network=host -e model_host=http://localhost:4242 monabraeunig/test-surrogate:latest
          
      - name: Save environment variables
        run: |
          echo "IMAGE_NAME=monabraeunig/surrogate-container2:latest" >> $GITHUB_ENV
