name: CI

on:
  push:
    branches:
      - 'main'
job:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        run: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: custom_surrogate/
          push: true
          #hier muss der container bzw das image auf dockerhub liegen
          tags: monabraeunig/surrogate-pch:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      model:
        #das ist wieder das docker image
        image: monabraeunig/surrogate-pch:latest
        ports:
        - 4242:4242

    steps:
       -
        name: Validate
        #hier muss vermutlich noch der test als docker container laufen
        run: |
          docker run --network=host -e model_host=http://localhost:4242 monabraeunig/testing-protocol-conformity-current:latest
    
