name: CI

on:
  push:
    branches:
      - 'main'
#env:
  #NODE_VERSION: '20'  # Set Node.js version
  #ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker version
        run: docker --version
